### ISSUE TITLE
Add the URL of your server: What am i missing?

### ISSUE THREAD

**Issue by gbajaj** [kossiitkgp/email-to-slack#13]
Unfortunately I am not able to  set it up.

Where do we put the server url to be triggered when email arrives in slackbok?

Here is my setup
1) I am running a local server with ngrok and Forwarding request to the local sever. This works when calling POST on ngrok api
2) My emails are being fwd to the Slackbot.
3) My Slack app is installed 
3) "Activate Incoming Webhooks" is done and working 

What i am not able to figure out is how to trigger the server url. Could you please suggest what I might be missing!
Thanks

**Comment by xypnox** [comment]
Hi @gbajaj,

The step in Add the URL of your server refers to adding the URL in the request URL field in Event subscription. 

Thanks for this issue as it points out that the steps written in the repo are not chronological. I have modified the steps in a PR, the steps after setting up the server with the required env variables is:


### Setup of Event Subscription
 -  Navigate to "Sidebar -> Event Subscription" and turn on.
 -  Put the link to the deployed server in "Request URL".
 -  Subscribe to `message.im` in **Subscribe to events on behalf of users**

I hope this solves the issue!

**Comment by xypnox** [comment]
The PR is #14 and it has better detailed instructions, so you can review those as well.

**Comment by gbajaj** [comment]
Yes, i reached out to slack support and they gave the same reply and I was able to make it work. Thanks for this work

**Comment by xypnox** [comment]
I am closing this issue as the problem has been resolved.
