### ISSUE TITLE
git push heroku failure

### ISSUE THREAD

**Issue by bardolf69** [kossiitkgp/email-to-slack#17]
When I try to push to heroku I get this error "error: src refspec general-emails does not match any"

**Comment by mehdichaouch** [comment]
Hello @bardolf69,
It seams to be a [GIT problem](https://www.qwant.com/?q=heroku+error%3A+src+refspec+general-emails+does+not+match+any), did you try to re-clone the repository?

**Comment by bardolf69** [comment]
yeah got it sorted thanks
