### ISSUE TITLE
Improving logging and fixed fallback bug

### ISSUE THREAD

**Issue by berserker1** [kossiitkgp/email-to-slack#8]
**Fallback notification bug**
>Upon displaying of notification it cannot display the email attached and hence goes for fallback  which says something not so helpful.
Hence I improved the fallback text.
Now it says  ----> _An email by <email_sender>_

 **Improved logging for the server**
>This is to simplify debugging

**I am submitting a pull request for the above mentioned issues** 

**Added log for status code of WEBHOOK_URL**

**Comment by OrkoHunter** [comment]
@berserker1 About your observation with requests.post, did you check r.status_code and did it differ from the status code in the browser? I highly doubt that. Please share the snippet of your python code.

**Comment by berserker1** [comment]
Oh.. fine I did not see that..  MY bAD.
i will implement a try catch block and submit the pr

**Comment by OrkoHunter** [comment]
Cool! Technically you should always check the status code and put conditions for the expected and unexpected behavior.

**Comment by berserker1** [comment]
@OrkoHunter @thealphadollar
One more thing:
>I have added several print statements for logging. and refactoring Are there be some specific method for heroku, some specific guidelines or library we import (Like _import logs_) or writing print these statements are enough?
 
I am talking about medium-scale software. For this application I do not think we need some specific procedure like this as it is simple enough to handle (  _My thoughts only_ ) or should we?

**Comment by OrkoHunter** [comment]
We don't need a logging module here. print statements are fine.

A large software with multiple processes/modules/functions must have logging. A logging module also helps if you log with verbose level. This means that you give your users the option of `-v`, `-vv` or `-vvv`, etc. And while writing your "print statements", you define in which verbose level should this be printed.

**Comment by berserker1** [comment]
I will give brief description of the log style when I change the pr
